# Generated by Django 3.1 on 2020-09-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('log_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=100, unique=True)),
                ('semester', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=20)),
                ('bot_token', models.CharField(max_length=255, unique=True)),
                ('admin_user_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'log_course',
                'unique_together': {('course_name', 'department', 'semester', 'workspace_id')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('log_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_number', models.IntegerField()),
                ('registered_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
            ],
            options={
                'db_table': 'log_group',
                'unique_together': {('group_number', 'registered_course_id')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('log_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=100)),
                ('assignment_name', models.CharField(max_length=100)),
                ('due_by', models.DateTimeField()),
                ('homework_url', models.URLField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'log_assignment',
                'unique_together': {('team_id', 'assignment_name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('log_student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_unity_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(default=None, max_length=254, unique=True)),
                ('slack_user_id', models.CharField(max_length=100, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group')),
                ('registered_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
            ],
            options={
                'db_table': 'log_student',
                'unique_together': {('registered_course_id', 'email_id')},
            },
        ),
    ]
