# Generated by Django 3.1 on 2020-09-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='team_id',
            new_name='workspace_id',
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('workspace_id', 'assignment_name')},
        ),
    ]
