# Generated by Django 3.1 on 2020-09-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='department_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'department')},
        ),
    ]
