# Generated by Django 3.1 on 2020-09-08 03:48

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200907_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('log_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_num', models.IntegerField(unique=True)),
                ('project_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'log_group',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('log_student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_unity_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group')),
                ('registered_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
            ],
            options={
                'db_table': 'log_student',
            },
        ),
        migrations.CreateModel(
            name='partOf',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('members', django_mysql.models.ListCharField(models.CharField(max_length=10, unique=True), max_length=55, size=5)),
                ('group_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group')),
            ],
            options={
                'db_table': 'log_partOf',
            },
        ),
    ]
