# Generated by Django 3.1 on 2020-09-08 04:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_group_partof_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10, unique=True), default=None, max_length=55, size=5),
            preserve_default=False,
        ),
    ]
