# Generated by Django 3.1 on 2020-09-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_partof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
