# Generated by Django 3.1 on 2020-09-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='partof',
            name='registered_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course'),
        ),
    ]
