# Generated by Django 3.1 on 2020-09-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
