# Generated by Django 3.1 on 2020-09-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_group_members'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'department', 'semester')},
        ),
    ]
