# Generated by Django 3.1 on 2020-09-20 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_partof_registered_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group'),
        ),
        migrations.DeleteModel(
            name='PartOf',
        ),
    ]
