# Generated by Django 3.1 on 2020-09-20 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200920_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.CreateModel(
            name='PartOf',
            fields=[
                ('log_pof_id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='api.group')),
                ('registered_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'log_partOf',
                'unique_together': {('group',)},
            },
        ),
    ]
