# Generated by Django 3.1 on 2020-09-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200908_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='project_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
