# Generated by Django 3.1 on 2020-09-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200920_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(null=True, to='api.Group'),
        ),
        migrations.DeleteModel(
            name='PartOf',
        ),
    ]
