# Generated by Django 3.1 on 2020-09-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200909_2147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'department', 'semester')},
        ),
    ]
