# Generated by Django 3.1 on 2020-09-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200909_2147'),
        ('api', '0003_auto_20200906_2156'),
    ]

    operations = [
    ]
