# Generated by Django 3.1 on 2020-09-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20200910_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='workspace_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'department', 'semester', 'workspace_id')},
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
    ]
