# Generated by Django 3.1 on 2020-09-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200910_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='bot_token',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='group',
            name='registered_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='slack_user_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('group_num', 'registered_course_id')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('registered_course_id', 'email_id')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
    ]
