# Generated by Django 3.1 on 2020-09-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200911_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slack_user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
