# Generated by Django 3.1 on 2020-09-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200911_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='workspace_id',
            field=models.CharField(default=-1, max_length=100, unique=True),
        ),
    ]
