# Generated by Django 3.1 on 2020-09-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200911_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admin_user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='bot_token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='workspace_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
