# Generated by Django 3.1 on 2020-09-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200911_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='bot_token',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='workspace_id',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
