# Generated by Django 3.1 on 2020-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200911_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('log_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=100)),
                ('assignment_name', models.CharField(max_length=100)),
                ('due_by', models.DateTimeField()),
                ('homework_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_assignment',
                'unique_together': {('team_id', 'assignment_name')},
            },
        ),
    ]
