# Generated by Django 3.1 on 2020-09-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200911_0458'),
        ('api', '0020_assignment_created_by'),
    ]

    operations = [
    ]
