# Generated by Django 3.1 on 2020-09-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200912_0308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='partOf',
        ),
    ]
