# Generated by Django 3.1 on 2020-09-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackCred',
            fields=[
                ('log_slack_team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=100)),
                ('workspace_name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'log_slack_team',
            },
        ),
    ]
