# Generated by Django 3.1 on 2020-09-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackcred',
            name='team_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
