# Generated by Django 3.1 on 2020-09-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_service', '0002_auto_20200905_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackcred',
            name='bot_communication_token',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
