# Generated by Django 3.1 on 2020-09-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_service', '0004_botserverendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandRequest',
            fields=[
                ('request_status', models.CharField(auto_created=True, choices=[('registered', 'Registered'),
                                                                                ('completed', 'Completed'),
                                                                                ('invalid', 'Invalid'),
                                                                                ('other', 'Other')],
                                                    default='registered', max_length=100)),
                ('is_valid_request', models.BooleanField(auto_created=True, default=True)),
                ('log_command_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('command', models.CharField(max_length=20)),
                ('command_parameters', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_time', models.BigIntegerField(blank=True, default=None, null=True)),
                ('end_time', models.BigIntegerField(blank=True, default=None, null=True)),
                ('response_time', models.BigIntegerField(blank=True, default=None, null=True)),
                ('response', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'db_table': 'log_command_request',
            },
        ),
        migrations.DeleteModel(
            name='BotServerEndpoint',
        ),
        migrations.DeleteModel(
            name='SlackCred',
        ),
    ]
